version: "2"
plugins:
  eslint:
    enabled: true
    config:
      config: .eslintrc.json
checks:
  method-complexity:
    enabled: false
  similar-code:
    enabled: false
  method-lines:
    enabled: false
  identical-code:
    enabled: false
