// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const VERIFY_EMAIL_SUCCESSFUL = 'VERIFY_EMAIL_SUCCESSFUL';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';
export const VERIFY_EMAIL_SUCCESSFUL_TOKEN = 'VERIFY_EMAIL_SUCCESSFUL_TOKEN';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const RESET_PASSWORD_REQUEST_SUCCESSFUL = 'RESET_PASSWORD_REQUEST_SUCCESSFUL';
export const RESET_PASSWORD_REQUEST_FAILED = 'RESET_PASSWORD_REQUEST_FAILED';
export const RESET_PASSWORD_UPDATE_SUCCESSFUL = 'RESET_PASSWORD_UPDATE_SUCCESSFUL';
export const RESET_PASSWORD_UPDATE_FAILED = 'RESET_PASSWORD_UPDATE_FAILED';
export const SET_CURRENT_USER_IMAGE = 'SET_CURRENT_USER_IMAGE';

// modal actions
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

// Profile
export const GET_PROFILE_BEGINS = 'GET_PROFILE_BEGINS';
export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILURE = 'GET_PROFILE_FAILURE';
export const GET_USER_ARTICLE_SUCCESS = 'GET_USER_ARTICLE_SUCCESS';
export const GET_USER_ARTICLE_FAILURE = 'GET_USER_ARTICLE_FAILURE';
export const EDIT_PROFILE_BEGINS = 'EDIT_PROFILE_BEGINS';
export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILURE = 'EDIT_PROFILE_FAILURE';
export const GET_USER_FOLLOWERS_SUCCESS = 'GET_USER_FOLLOWERS_SUCCESS';
export const GET_USER_FOLLOWERS_FAILURE = 'GET_USER_FOLLOWERS_FAILURE';
export const GET_USER_FOLLOWING_SUCCESS = 'GET_USER_FOLLOWING_SUCCESS';
export const GET_USER_FOLLOWING_FAILURE = 'GET_USER_FOLLOWING_FAILURE';

// social login
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';
export const CREATE_ARTICLE_BEGINS = 'CREATE_ARTICLE_BEGINS';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_REJECTED = 'CREATE_ARTICLE_REJECTED';

export const GET_FEATURED_AUTHOR = 'GET_FEATURED_AUTHOR';
export const GET_FEATURED_AUTHOR_FAIL = 'GET_FEATURED_AUTHOR_FAIL';
