// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const VERIFY_EMAIL_SUCCESSFUL = 'VERIFY_EMAIL_SUCCESSFUL';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';
export const VERIFY_EMAIL_SUCCESSFUL_TOKEN = 'VERIFY_EMAIL_SUCCESSFUL_TOKEN';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';
export const RESET_PASSWORD_REQUEST_SUCCESSFUL = 'RESET_PASSWORD_REQUEST_SUCCESSFUL';
export const RESET_PASSWORD_REQUEST_FAILED = 'RESET_PASSWORD_REQUEST_FAILED';
export const RESET_PASSWORD_UPDATE_SUCCESSFUL = 'RESET_PASSWORD_UPDATE_SUCCESSFUL';
export const RESET_PASSWORD_UPDATE_FAILED = 'RESET_PASSWORD_UPDATE_FAILED';

// modal actions
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

// social login
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';
export const CREATE_ARTICLE_BEGINS = 'CREATE_ARTICLE_BEGINS';
export const CREATE_ARTICLE = 'CREATE_ARTICLE';
export const CREATE_ARTICLE_FAIL = 'CREATE_ARTICLE_FAIL';
export const CREATE_ARTICLE_REJECTED = 'CREATE_ARTICLE_REJECTED';
