// auth actions
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const SIGN_UP_ERRORS = 'SIGN_UP_ERRORS';
export const SIGN_UP_SUCCESS = 'SIGN_UP_SUCCESS';
export const LOGOUT_USER = 'LOGOUT_USER';
export const VERIFY_EMAIL_SUCCESSFUL = 'VERIFY_EMAIL_SUCCESSFUL';
export const VERIFY_EMAIL_FAILED = 'VERIFY_EMAIL_FAILED';
export const VERIFY_EMAIL_SUCCESSFUL_TOKEN = 'VERIFY_EMAIL_SUCCESSFUL_TOKEN';
export const SET_CURRENT_USER_FAIL = 'SET_CURRENT_USER_FAIL';

// modal actions
export const SHOW_SIGNUP_MODAL = 'SHOW_SIGNUP_MODAL';
export const HIDE_SIGNUP_MODAL = 'HIDE_SIGNUP_MODAL';
export const DELETE_ERROR_MESSAGE = 'DELETE_ERROR_MESSAGE';
export const SHOW_LOGIN_MODAL = 'SHOW_LOGIN_MODAL';
export const HIDE_LOGIN_MODAL = 'HIDE_LOGIN_MODAL';

// social login
export const SOCIAL_LOGIN_SUCCESS = 'SOCIAL_LOGIN_SUCCESS';
export const SOCIAL_LOGIN_ERROR = 'SOCIAL_LOGIN_ERROR';
// follow actions
export const CREATE_FOLLOW_RELATIONSHIP = 'CREATE_FOLLOW_RELATIONSHIP';
export const DELETE_FOLLOW_RELATIONSHIP = 'DELETE_FOLLOW_RELATIONSHIP';
export const GET_ALL_FOLLOWERS = 'GET_ALL_FOLLOWERS';
export const GET_ALL_FOLLOWING = 'GET_ALL_FOLLOWING';
export const FOLLOW_ERRORS = 'FOLLOW_ERRORS';
